#!/bin/bash


clone() {
	echo
	echo "input repo link"
	read -p ">> " link
	git clone $link
}

commit() {
	echo
	echo "input commit message"
	read -p ">> " msg
	git commit -m $msg
}

publish() {
	echo
	echo "your P.A.T. is"
	echo $PAT
	git push origin main
}

dispat() {
	echo
	echo "your P.A.T. is"
	echo $PAT
	echo
}

status() {
	echo
	git status
}

addfiles() {
	echo
	echo "input files to add/change"
	read -p ">> " chng
	git add $chng
}

menu() {
	echo
        echo "[1] Clone Repo [2] Commit Changes [3] Publish Changes [4] Display P.A.T. [5] Check Status [6] Add files/changes [7] Exit"
        echo
        read -p ">> " choice

        if [ $choice == "1" ]; then
                clone
		menu
        elif [ $choice == "2" ]; then
                commit
		menu
        elif [ $choice == "3" ]; then
                publish
		menu
        elif [ $choice == "4" ]; then
                dispat
		menu
        elif [ $choice == "5" ]; then
                status
		menu
	elif [ $choice == "6" ]; then
		addfiles
		menu
	elif [ $choice == "7" ]; then
		clear
		echo "goodbye :)"
        else
                echo "invalid input"
                menu
        fi

}

init() {
    echo
    cat << "EOF"
⣴⡿⠶⠀⠀⠀⣦⣀⣴⠀⠀⠀⠀
⣿⡄⠀⠀⣠⣾⠛⣿⠛⣷⠀⠿⣦
⠙⣷⣦⣾⣿⣿⣿⣿⣿⠟⠀⣴⣿
⠀⣸⣿⣿⣿⣿⣿⣿⣿⣾⠿⠋⠁
⠀⣿⣿⣿⠿⡿⣿⣿⡿⠀⠀⠀⠀
⢸⣿⡋⠀⠀⠀⢹⣿⡇⠀⠀⠀⠀
⣿⡟⠀⠀⠀⠀⠀⢿⡇⠀⠀⠀⠀
⠉⠁⠀⠀⠀⠀⠀⠸⠇⠀⠀⠀⠀
EOF
    echo
    echo "lazygit"
    echo "by ShadowNetter"
    echo
    menu
}

init
